export default {
  Colors: {
    BACKGROUND: '#000000',
    BACKGROUND_THEME: '#000000',
    BACKGROUND_HEADER: '#333333',
    BACKGROUND_MENU_SELECTED: '#000000',
    FONT_COLOR_DARK: '#FFFF00',
    ICON_COLOR: '#FFFF00',
    ICON_COLOR_HEADER: '#FFFF00',
    INPUT_BORDER_COLOR: '#FFFF00',
    PLACEHOLDER_INPUT_COLOR: '#FFFF00',
    BUTTON_COLOR: '#000000',
    BORDER_BUTTON_COLOR: '#FFFF00',
    TEXT_CLICKABLE: '#FFFF00',
    TEXT_USERNAME_PRIMARY: '#FFFFFF',
    TEXT_USERNAME_SECONDARY: '#FFFFFF',
  },

  Sizes: {
    ICON_SIZE: 20,
    ICON_SIZE_HEADER: 25,
    ICON_SIZE_MENU: 25,
    INPUT_SIZE: 18,
    TEXT_SIZE_TITLE: 30,
    TEXT_SIZE_SUBTITLE: 20,
    TEXT_SIZE_USERNAME_PRIMARY: 20,
    TEXT_SIZE_USERNAME_SECONDARY: 16,
  },
};
