export default {
  Colors: {
    BACKGROUND: '#FFFFFF',
    BACKGROUND_THEME: '#3490DC',
    BACKGROUND_HEADER: '#3490DC',
    BACKGROUND_MENU_SELECTED: '#42617A',
    FONT_COLOR_DARK: '#000000',
    ICON_COLOR: '#3490DC',
    ICON_COLOR_HEADER: '#FFFFFF',
    INPUT_BORDER_COLOR: '#3490DC',
    PLACEHOLDER_INPUT_COLOR: '#C5C5C5',
    BUTTON_COLOR: '#3490DC',
    BORDER_BUTTON_COLOR: '#FFFFFF',
    TEXT_CLICKABLE: '#FFFFFF',
    TEXT_USERNAME_PRIMARY: '#FFFFFF',
    TEXT_USERNAME_SECONDARY: '#FFFFFF',
  },

  Sizes: {
    ICON_SIZE: 20,
    ICON_SIZE_HEADER: 25,
    ICON_SIZE_MENU: 25,
    INPUT_SIZE: 18,
    TEXT_SIZE_TITLE: 30,
    TEXT_SIZE_SUBTITLE: 20,
    TEXT_SIZE_USERNAME_PRIMARY: 20,
    TEXT_SIZE_USERNAME_SECONDARY: 16,
  },
};
